# Generated by Django 6.0.1 on 2026-02-26 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('modern', 'Modern'), ('corporate', 'Corporate'), ('creative', 'Creative'), ('fresher', 'Fresher'), ('tech', 'Tech Developer'), ('government', 'Government Job')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('career_objective', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('certifications', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
