# Generated by Django 6.0.1 on 2026-03-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
