# Generated by Django 6.0.1 on 2026-03-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('minimalist', 'Minimalist'), ('dynamic', 'Dynamic'), ('creative', 'Creative'), ('essential', 'Essential'), ('modest', 'Modest'), ('bold', 'Bold')], max_length=20),
        ),
    ]
